### ISSUE TITLE
release the code

### ISSUE THREAD

**Issue by Jee-King** [Xiaoqi-Zhao-DLUT/DANet-RGBD-Saliency#1]
Hi,  thanks for your great work.
Do you have a plan to release your code?

**Comment by Xiaoqi-Zhao-DLUT** [comment]
@Jee-King  Thank you for your appreciation of our work！ As we are currently using our algorithm in a related competition, we will release the code around November. (Both DANet and GateNet)

**Comment by Jee-King** [comment]
ok
thanks
